package model

type AddVserver struct {
	Title  string        `json:"title"`
	Error  []interface{} `json:"error"`
	VsInfo struct {
		UUID             string        `json:"uuid"`
		Pass             string        `json:"pass"`
		Plid             int           `json:"plid"`
		Hostname         string        `json:"hostname"`
		Space            int           `json:"space"`
		RAM              int           `json:"ram"`
		Bandwidth        int           `json:"bandwidth"`
		NetworkSpeed     int           `json:"network_speed"`
		UploadSpeed      int           `json:"upload_speed"`
		Cores            int           `json:"cores"`
		Cpupin           int           `json:"cpupin"`
		UID              string        `json:"uid"`
		Io               int           `json:"io"`
		Burst            int           `json:"burst"`
		CPUPercent       int           `json:"cpu_percent"`
		Swap             int           `json:"swap"`
		Acpi             int           `json:"acpi"`
		Apic             int           `json:"apic"`
		Pae              int           `json:"pae"`
		Vnc              int           `json:"vnc"`
		Vncport          int           `json:"vncport"`
		Shadow           int           `json:"shadow"`
		Virt             string        `json:"virt"`
		Hvm              int           `json:"hvm"`
		Iso              string        `json:"iso"`
		Boot             string        `json:"boot"`
		BandSuspend      int           `json:"band_suspend"`
		SpeedCapDown     int           `json:"speed_cap_down"`
		SpeedCapUp       int           `json:"speed_cap_up"`
		Tuntap           int           `json:"tuntap"`
		Ppp              int           `json:"ppp"`
		MacStatus        int           `json:"mac_status"`
		OsreinstallLimit int           `json:"osreinstall_limit"`
		Mg               []interface{} `json:"mg"`
		KvmCache         string        `json:"kvm_cache"`
		IoMode           string        `json:"io_mode"`
		VncKeymap        string        `json:"vnc_keymap"`
		Virtio           int           `json:"virtio"`
		Numa             int           `json:"numa"`
		CPUMode          string        `json:"cpu_mode"`
		AdminManaged     int           `json:"admin_managed"`
		Rdp              int           `json:"rdp"`
		DisableNwConfig  int           `json:"disable_nw_config"`
		TopologySockets  int           `json:"topology_sockets"`
		TopologyCores    int           `json:"topology_cores"`
		TopologyThreads  int           `json:"topology_threads"`
		OpenvzFeatures   string        `json:"openvz_features"`
		Bpid             int           `json:"bpid"`
		InstallXentools  int           `json:"install_xentools"`
		SecIso           string        `json:"sec_iso"`
		Mac              string        `json:"mac"`
		Osid             int           `json:"osid"`
		CPU              int           `json:"cpu"`
		KvmVga           int           `json:"kvm_vga"`
		Acceleration     int           `json:"acceleration"`
		Vncpass          string        `json:"vncpass"`
		DisableEbtables  int           `json:"disable_ebtables"`
		Webuzo           int           `json:"webuzo"`
		NicType          string        `json:"nic_type"`
		VifType          string        `json:"vif_type"`
		VpsName          string        `json:"vps_name"`
		Ubc              string        `json:"ubc"`
		Vpsid            string        `json:"vpsid"`
		Disks            []struct {
			Primary    int    `json:"primary"`
			Path       string `json:"path"`
			StUUID     string `json:"st_uuid"`
			Type       string `json:"type"`
			Size       string `json:"size"`
			SizeUnit   string `json:"size_unit"`
			Vpsid      string `json:"vpsid"`
			Rescue     int    `json:"rescue"`
			TargetName string `json:"target_name"`
			Format     string `json:"format"`
			DiskUUID   string `json:"disk_uuid"`
			Num        int    `json:"num"`
		} `json:"disks"`
		Ips        []string      `json:"ips"`
		Ipv6       []interface{} `json:"ipv6"`
		Ipv6Subnet []interface{} `json:"ipv6_subnet"`
		IpsInt     []interface{} `json:"ips_int"`
	} `json:"vs_info"`
	Globals struct {
		CookieName string `json:"cookie_name"`
	} `json:"globals"`
}
