name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
       go-version: '1.21'

    - name: Build app 
      run: go build -o main main.go

    - name: SCP to Server
      uses: appleboy/scp-action@master
      with:
       host: ${{ GO_HOST }}
       username: ${{ GO_USER }}
       password: ${{ GO_PWD }}
       port: 2222
       source: "main"         
       target: "/opt/apigo"
   
    - name: Deploy and rebuild on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ GO_HOST }}
        username: ${{ GO_USER }}
        password: ${{ GO_PWD }}
        port: 2222
        script:           
         systemctl restart dnicapi &&
         systemctl status dnicapi
