name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
       go-version: '1.21'

    - name: Build app 
      run: go build -o main main.go

    - name: SCP to Server
      uses: appleboy/scp-action@master
      with:
       host: ${{ secrets.HOST }}
       username: ${{ secrets.USER }}
       password: ${{ secrets.PWD }}
       port: 22
       source: "."         
       target: "/opt/apps/apigo"
   
    - name: Deploy and rebuild on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PWD }}
        port: 22
        script:           
         systemctl restart dnicapi &&
         systemctl status dnicapi
