runs-on: ubuntu-latest
on: [push]
# Steps represent a sequence of tasks that will be executed as part of the job
steps:
# Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
- name: Checkout the repository
  uses: actions/checkout@v2

- name: Set up Go 1.13
  uses: actions/setup-go@v1
  with: 
    go-version: 1.13         

- name: Build app 
  run: go build -o app main.go

- name: SCP to Ocean
  uses: appleboy/scp-action@master
  with:
    host: ${{ GO_HOST }}
    username: ${{ GO_USER }}
    password: ${{ GO_PWD }}
    port: 2222
    source: "app"         
    target: "dist"    

- name: Deploy and rebuild on server
  uses: appleboy/ssh-action@master
  with:
    host: ${{ GO_HOST }}
    username: ${{ GO_USER }}
    password: ${{ GO_PWD }}
    port: 2222
    script:           
      systemctl restart goweb.service &&
      systemctl status goweb
